### ISSUE TITLE
3rd party providers support

### ISSUE THREAD

**Issue by JounQin** [antfu/sponsorkit#21]
### Clear and concise description of the problem

As title

### Suggested solution

As title

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by citizens-bank-pro** [comment]
#21 what good

**Comment by sifferhans** [comment]
@JounQin Any providers you have in mind?

**Comment by jahirfiquitiva** [comment]
[Buy me a coffee](https://developers.buymeacoffee.com/#/apireference?id=all-supporters) would be a great addition @antfu
