### ISSUE TITLE
Display the past sponsors.

### ISSUE THREAD

**Issue by dohooo** [antfu/sponsorkit#25]
### Clear and concise description of the problem

Maybe we can display the past sponsors because I saw GitHub shows it in the sponsor profile.

### Suggested solution

```
    {
      title: 'Past Sponsors',
      monthlyDollars: -1,
      preset: presets.base,
    },
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by dohooo** [comment]
Is this ok? I can submit a PR.  @antfu

**Comment by antfu** [comment]
Sure, PR welcome

**Comment by dohooo** [comment]
However, It seems GitHub doesn't get past sponsorships from grapgql. The official doesn't add new fields for this feature. But I think we can use `playwright` for this. 
 
<img width="666" alt="image" src="https://user-images.githubusercontent.com/32405058/200243812-4a878f5e-6520-49af-912f-440d7e5656cf.png">

<img width="262" alt="image" src="https://user-images.githubusercontent.com/32405058/200243879-9114b604-894c-4f75-866c-8fee688b3166.png">

We can get the username from here. What do you think?

**Comment by antfu** [comment]
Using Playwright is probably not a good option for us. We might better request GitHub to expose that API.

**Comment by dohooo** [comment]
I have asked about this. It seems doesn't want to support this, there have nobody replied to that question.

**Comment by dohooo** [comment]
> Using Playwright is probably not a good option for us. We might better request GitHub to expose that API.

I can create a package to get past sponsorships, and we can import this package into sponsorkit. Then we'll replace it when GitHub exposes that API.

**Comment by dohooo** [comment]
[released](https://www.npmjs.com/package/get-past-sponsors), So can I add this feature?

There are some discussions for this feature request. 
https://github.com/community/community/discussions/38393
https://github.com/community/community/discussions/37234
