### ISSUE TITLE
OpenCollective should use monthly amount instead of total

### ISSUE THREAD

**Issue by andreynering** [antfu/sponsorkit#28]
### Describe the bug

I just tried this by adding both GitHub Sponsors and Open Collective tokens. The way this tool handle each is different.

For GitHub, it's taking into account the monthly value (as it should), but for Open Collective it's using the total, which results is a wrong output image.

### Reproduction

Use GitHub and OpenCollective at the same time and see that they use different values.

### System Info

```Shell
System:
    OS: macOS 12.6
    CPU: (10) arm64 Apple M1 Pro
    Memory: 89.61 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    Yarn: 1.22.18 - ~/.nvm/versions/node/v16.13.1/bin/yarn
    npm: 8.6.0 - ~/.nvm/versions/node/v16.13.1/bin/npm
  Browsers:
    Brave Browser: 101.1.38.115
    Chrome: 108.0.5359.94
    Firefox: 107.0.1
    Firefox Developer Edition: 108.0
    Safari: 16.0
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
I don't use OC much and don't have enough data to test. It would be great if you could identify the issue and send a PR. Thanks.

**Comment by andreynering** [comment]
I tried the fix the it's still considering the all time donated value instead of monthly.

Also, sponsorkit is unable to detect past sponsors from OpenCollective and show then as active sponsors.

Sorry, I'm trying to be demanding, I'm just reporting a bug 🙂 I'll consider using this for GitHub Sponsors only for now.
