### ISSUE TITLE
Support custom provider for wechat, alipay, etc.

### ISSUE THREAD

**Issue by ModyQyW** [antfu/sponsorkit#30]
### Clear and concise description of the problem

Now `sponsorkit` only supports platform sponsors. It is hard to add sponsors sponsored by wechat, alipay, etc.

### Suggested solution

We can specify a file read by `unconfig`, named `custom-sponsors.config.ts` or something. The file exports sponsors, matching type `Sponsorship[]`.

### Additional context

This is a raw idea. I will make a pr if this idea is possible.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
You could use this hook to append custom sponsors:
https://github.com/antfu/sponsorkit/blob/f39c69323fc9e239cce527c90ed3be4149675588/src/types.ts#L187-L190

**Comment by ModyQyW** [comment]
Totally miss that. Sorry.
