### ISSUE TITLE
OpenCollective subscriptions don't expire

### ISSUE THREAD

**Issue by fb55** [antfu/sponsorkit#40]
### Describe the bug

sponsorkit fetches the members of a collective on OpenCollective. This includes previous sponsors that are no longer active.

Additionally, the monthly amount is also off: 

On OpenCollective, it is possible to change the amount associated with a tier on OpenCollective (unlike GitHub Sponsors, which requires tiers to be retired to change their amounts). The currently logic will return the current amount of the tier, not the amount actually payed by the sponsor.

If a sponsor didn't pay as part of a tier, then the total amount contributed by that sponsor is returned as the monthly price, which will lead to a much higher placement in the tiers.

The same applies to individual accounts (#32).

### Reproduction

Fetch sponsors for https://opencollective.com/cheerio

### System Info

```Shell
sponsorkit@0.8.2
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by fb55** [comment]
My suggested workaround is to always use `orders`, and only include active ones. Here is the relevant call in Cheerio's current implementation:

https://github.com/cheeriojs/cheerio/blob/20b29983cf937d0ff700cb642cc0453b208e208e/scripts/fetch-sponsors.mts#L73-L97

Note that this only includes public information, so the OpenCollective API key could be dropped.

**Comment by MichalLytek** [comment]
I've encountered a similar issue.
Until it's resolved, I have to maintain the sponsors table in readme manually and use this tool only for GitHub Sponsors 😕

**Comment by kecrily** [comment]
It's been a bit of time since I've paid attention to this project, I'll try to solve this problem when I'm free.

**Comment by robingenz** [comment]
This issue could be fixed in the latest version by #58.

**Comment by carlocorradini** [comment]
Awesome 😎
