### ISSUE TITLE
Text overlaping on presets.large

### ISSUE THREAD

**Issue by GeopJr** [antfu/sponsorkit#45]
### Describe the bug

Text overlaps on presets.large, similar to #3: https://github.com/GeopJr/GeopJr/blob/main/sponsors.svg

It was generated using GitHub actions on the [`latest` tag](https://github.com/GeopJr/GeopJr/blob/main/package.json#L8) using [this config](https://github.com/GeopJr/GeopJr/blob/main/sponsorkit.config.js) and [this action workflow](https://github.com/GeopJr/GeopJr/blob/main/.github/workflows/sponsorkit.yml)

### Reproduction

The above mentioned workflow, config and github login should reproduce it

### System Info

```Shell
(This is from action runner)


  System:
    OS: Linux 5.15 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (2) x64 Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz
    Memory: 5.86 GB / 6.78 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.15.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.5.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 111.0.5563.146
    Chromium: 111.0.5547.0
    Firefox: 111.0.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
I am not sure how we could properly fix it. Currently we limit the length of the name by string length but we probably need to introduce some library to measure their visual width instead.

**Comment by GeopJr** [comment]
I don't think measuring its width would work either since there are multiple fonts. I did some attempts with clip paths and nested svgs:

```svg
<!-- the math is a bit weird, svg x + text x should be equal to the original x (same for y) -->
<!-- 70 is the width and height of the avatar -->
<svg width="70" height="70" x="282.5" y="83" xmlns="http://www.w3.org/2000/svg">
      <text x="70" y="70" text-anchor="middle" class="sponsorkit-name" fill="currentColor">Andreas Maerten</text>
</svg>
```

![image](https://user-images.githubusercontent.com/18014039/231476145-00df4745-9d9c-482e-88c8-f7b22112d3d6.png)

That looks a bit bad, but if we increase the x so its a bit more centered and the width since it fits:

```svg
<svg width="70" height="70" y="83" xmlns="http://www.w3.org/2000/svg" x="315">
      <text y="70" text-anchor="middle" class="sponsorkit-name" fill="currentColor" x="52.5">Andreas Maerten</text>
</svg>
```

![image](https://user-images.githubusercontent.com/18014039/231477283-b478dd6f-f80f-4a87-9535-dcf9762411ca.png)

:/ The half-missing word doesn't look that good either. Using `foreignobject` for text wrapping would also break the svg outside of browsers.

For my original issue, I'll just decrease the preset maxLength, so feel free to close!
