### ISSUE TITLE
Patreon not saving sponsors

### ISSUE THREAD

**Issue by anubra266** [antfu/sponsorkit#49]
### Describe the bug

Patreon sponsors are not saved

### Reproduction

https://github.com/anubra266/static

### System Info

```Shell
Github action and locally
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
I'd have Patreon to test, feel free to investigate and send PR if you find the fix.
