### ISSUE TITLE
Allow to provide raw entries manually

### ISSUE THREAD

**Issue by endel** [antfu/sponsorkit#55]
### Clear and concise description of the problem

I have a use case where the company will "sponsor" privately. There will be no records of it on Patreon / GitHub / etc. It would be great to allow providing a raw list of sponsors that are maintained manually.

### Suggested solution

I think this could be implemented either via a "JSON" provider - that reads the contents from a JSON file, or manual entries that could be placed directly on the `sponsor.config.ts` file.

The advantage of using the `sponsor.config.ts` is that auto-completion would make it easy to manually write entries. Implementing via JSON provider in the other hand would allow _some_ custom automation to generate the raw entries.

### Additional context

Please let me know what you think, I'd love to contribute with a PR for this.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
You can use these two hooks to inject your own entries:
https://github.com/antfu/sponsorkit/blob/4b3e67548662c789a400d83165ecf11427cd9165/src/types.ts#L209-L217
The input arguments are mutable.

**Comment by endel** [comment]
That's perfect, thank you! 🙏
