### ISSUE TITLE
GitHub Tier is null

### ISSUE THREAD

**Issue by jycouet** [antfu/sponsorkit#60]
### Describe the bug

When I launch `sponsorkit`, I get this error:
```
TypeError: Cannot read properties of null (reading 'isOneTime')
    at xxx/node_modules/.pnpm/sponsorkit@0.9.1/node_modules/sponsorkit/dist/index.cjs:478:25
```

Looking more into it, it seems that GitHub is returning `null` to the `tier` field now!

```gql
query {
  organization(login: "MY_ORG") {
    sponsorshipsAsMaintainer(first: 100) {
      totalCount
      pageInfo {
        endCursor
        hasNextPage
      }
      nodes {
        createdAt
        privacyLevel
        tier {             # <-- This field is null
          name
          isOneTime
          monthlyPriceInCents
          monthlyPriceInDollars
        }
        sponsorEntity {
          __typename
          ...on Organization {
            login
            name
            avatarUrl
            websiteUrl
          }
          ...on User {
            login
            name
            avatarUrl
            websiteUrl
          }
        }
      }
    }
  }
}
```
I did check in the online https://docs.github.com/en/graphql/overview/explorer of github, and yes, I get all sponsors, but no `tier` information (it's null).

I don't know from when, as it was working well before 👍
Any idea of where to ask for GitHub API changes ?

Should this case of `tier null` be handle? (I could do a PR, but I'm not sure it's wanted... as we lose a lot of info.)
Let me know

### Reproduction

https://github.com/HoudiniGraphql/sponsors

### System Info

```Shell
System:
    OS: macOS 14.2.1
    CPU: (12) arm64 Apple M3 Pro
    Memory: 372.11 MB / 36.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.2.0 - ~/.nvm/versions/node/v21.2.0/bin/node
    Yarn: 1.22.21 - ~/.nvm/versions/node/v21.2.0/bin/yarn
    npm: 10.2.3 - ~/.nvm/versions/node/v21.2.0/bin/npm
    pnpm: 8.10.5 - ~/Library/pnpm/pnpm
    bun: 1.0.12 - ~/.bun/bin/bun
  Browsers:
    Chrome: 121.0.6167.160
    Safari: 17.2.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by farfromrefug** [comment]
I am having the same issue

**Comment by jycouet** [comment]
It's most likely because of token rights I think.

**Comment by antfu** [comment]
I am up to provide a better error message in this case to guide users to update their token permissions. PR welcome

**Comment by farfromrefug** [comment]
So what do we need to update ? Which permission is missing ?

**Comment by antfu** [comment]
I don't really know - I don't have such issue on my side. You might double check the docs to see if you missed anything and help us figure out what we could improve

**Comment by farfromrefug** [comment]
@antfu Yes i checked ans i hâve thé 2 needed permissions. I should mention it was working 6days ago. So a new permission might be needed.

**Comment by farfromrefug** [comment]
@antfu i think i found the issue. Even with the correct permissions some `sponsorshipsAsMaintainer.nodes` can be returned with null `tier`. I am not sure why this is on github side. For me only one node has null `tier`.
I fixed it locally by filtering nodes for non null tier.
I created a PR. Hoping you are going to accept it
