### ISSUE TITLE
`sponsorkit@0.9.3` is not published on npm

### ISSUE THREAD

**Issue by SukkaW** [antfu/sponsorkit#63]
### Describe the bug

The latest version of `sponsorkit` on npm is still `0.9.1`

### Reproduction

https://www.npmjs.com/package/sponsorkit?activeTab=versions

### System Info

```Shell
System:
    OS: macOS 14.4
    CPU: (12) arm64 Apple M2 Max
    Memory: 1.34 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.19.0 - ~/Library/Caches/fnm_multishells/31908_1710819745664/bin/node
    Yarn: 1.22.21 - ~/Library/Caches/fnm_multishells/31908_1710819745664/bin/yarn
    npm: 10.2.3 - ~/Library/Caches/fnm_multishells/31908_1710819745664/bin/npm
    pnpm: 8.15.4 - ~/Library/Caches/fnm_multishells/31908_1710819745664/bin/pnpm
    bun: 1.0.31 - ~/.npm-global/bin/bun
  Browsers:
    Chrome: 122.0.6261.129
    Chrome Canary: 124.0.6366.1
    Safari: 17.4
```

### Used Package Manager

n/a

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
Weird - just did, thanks.
