### ISSUE TITLE
Polar.sh support

### ISSUE THREAD

**Issue by Julien-R44** [antfu/sponsorkit#65]
### Clear and concise description of the problem

Add a support for [Polar.sh](https://polar.sh/) provider to sponsorkit

### Suggested solution

I can work on a PR if you're OK with adding it to `sponsorkit` ! 

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
Sure, PR welcome :)
