### ISSUE TITLE
Bug: Afdian unexpected avatar and nickname

### ISSUE THREAD

**Issue by xiaodong2008** [antfu/sponsorkit#72]
### Describe the bug

Version 0.12.2

![sponsors](https://github.com/antfu-collective/sponsorkit/assets/84657208/0a564ab4-9d53-426c-b14e-64c60a07adeb)

Version 0.14.3(latest)

![sponsors wide](https://github.com/antfu-collective/sponsorkit/assets/84657208/3cfa704f-7c54-4189-8d30-0b141eb64c84)

### Reproduction

https://stackblitz.com/~/github.com/xiaodong2008/sponsors

### System Info

```Shell
System:
    OS: macOS 14.4
    CPU: (8) arm64 Apple M2
    Memory: 112.73 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
Binaries:
    Node: 20.12.2 - /opt/homebrew/opt/node@20/bin/node
    Yarn: 1.22.22 - /opt/homebrew/opt/node@20/bin/yarn
    npm: 10.5.0 - /opt/homebrew/opt/node@20/bin/npm
    pnpm: 8.15.7 - /opt/homebrew/opt/node@20/bin/pnpm
Browsers:
    Chrome: 124.0.6367.158
    Safari: 17.4
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### Contributions

- [X] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by xiaodong2008** [comment]
I saw that was edited in ce93d6aa681a375cef93fb582354d277a8e853f7, is this a expected result?

**Comment by antfu** [comment]
Yeah... I kinda think that was better - but I guess either ways they don't provide much information - Feel free to revert it if you prefer the old one

**Comment by xiaodong2008** [comment]
I think that we can just keep the default avatar, the new avatar looks so strange...

**Comment by antfu** [comment]
Would you like to send a quick PR? Thanks

**Comment by xiaodong2008** [comment]
Sure, here you go: #73
