### ISSUE TITLE
URL is sometimes without protocol

### ISSUE THREAD

**Issue by brc-dd** [antfu/sponsorkit#76]
### Describe the bug

`sponsor.websiteUrl` is sometimes without protocol. Maybe we should be normalizing that? Sindre has a package - [normalize-url](https://github.com/sindresorhus/normalize-url). If only the protocol normalization is needed we can just do try/catch ourselves.

### Reproduction

click on patak's avatar - https://cdn.jsdelivr.net/gh/antfu/static/sponsors.svg

### System Info

```Shell
System:
    OS: macOS 14.5
    CPU: (10) arm64 Apple M2 Pro
    Memory: 290.66 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
Binaries:
    Node: 22.2.0 - ~/.local/state/fnm_multishells/23263_1719152794371/bin/node
    npm: 10.7.0 - ~/.local/state/fnm_multishells/23263_1719152794371/bin/npm
    pnpm: 9.4.0 - ~/.local/state/fnm_multishells/23263_1719152794371/bin/pnpm
    bun: 1.1.13 - /opt/homebrew/bin/bun
Browsers:
    Safari: 17.5
    Safari Technology Preview: 17.4
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### Contributions

- [X] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by antfu** [comment]
Interesting - while I'd curious about when and why this would happend - but I guess doing a normalization won't hurt - would you like to send a quick PR? Thanks
