### ISSUE TITLE
prefer `href` over `xlink:href`

### ISSUE THREAD

**Issue by brc-dd** [antfu/sponsorkit#78]
### Clear and concise description of the problem

`xlink:href` was deprecated with svg 2 (around ~7 years back)

### Suggested solution

on svg anchor elements it's recommended to use `href` instead

### Additional context

browser compatibility is very slightly different -

for xlink:href - https://caniuse.com/mdn-svg_elements_a_xlink_href / https://caniuse.com/mdn-svg_elements_image_xlink_href - 96.32% usage
for href - https://caniuse.com/mdn-svg_elements_a_href / https://caniuse.com/mdn-api_svgimageelement_href - 96.37% usage

(href is slightly higher despite being standardized later is because ie11 supported it before others) 

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
Sure, up for it. I didn't remember why I picked it at the beginning tho, but they should work the same
