### ISSUE TITLE
[提议]：爱发电貌似被查了，现在官网和api调用都报错

### ISSUE THREAD

**Issue by everfu** [antfu/sponsorkit#81]
### Additional context

如题

**Comment by antfu** [comment]
所以你的提议是什么呢？

**Comment by antfu** [comment]
我这边看起来可以访问

**Comment by everfu** [comment]
> 我这边看起来可以访问

DNS 缓存吧，目前爱发电的ICP备案已经掉了

**Comment by everfu** [comment]
目前我的仓库action已经无法正常执行了
https://github.com/everfu/static/actions/runs/9949042244/job/27484653121

**Comment by AirboZH** [comment]
+1 我也没有办法正常使用了，目前 .com 域名可用
 [https://afdian.com/api/open/query-sponsor](https://afdian.com/api/open/query-sponsor)
但好像解析到了海外的云服务，可能也不是爱发电的长久之计

**Comment by everfu** [comment]
国内这种平台还是不好存活，避免不了被利用（估计是涉黄了）

**Comment by everfu** [comment]
![0d12b59e355108e70b072342ba5c487c](https://github.com/user-attachments/assets/b8bb4eca-dba4-4e6e-8b35-3a82795ff870)

**Comment by everfu** [comment]
可以准备移除api了

**Comment by antfu** [comment]
移除 API 倒是不必，暂时先别用就好了

**Comment by everfu** [comment]
> 移除 API 倒是不必，暂时先别用就好了

👌

**Comment by sxzz** [comment]
已更换为 afdian.com via #82
