### ISSUE TITLE
Possible regression in 0.16: `formats` is now mandatory

### ISSUE THREAD

**Issue by julien-deramond** [antfu/sponsorkit#98]
### Describe the bug

Hello there!

I've spotted a regression while bumping sponsorkit from 0.15.5 to 0.16.0 (and so, 0.16.1).
It's a regression from my point of view, but I can perfectly understand if you don't consider it is a regression. In that case, you can close this issue right away :)

The working version with 0.15.5 is the `main` branch of https://github.com/julien-deramond/static.
The issue happens within this PR https://github.com/julien-deramond/static/pull/7.

In order to execute it locally, you can:
```
pnpm i
SPONSORKIT_GITHUB_TOKEN=ghp_xxxxxxx SPONSORKIT_GITHUB_LOGIN=your_login pnpm build
# `SPONSORKIT_GITHUB_TOKEN=ghp_xxxxxx SPONSORKIT_GITHUB_LOGIN=julien-deramond pnpm build` for me
```

This will run https://github.com/julien-deramond/static/blob/main/build.sh which are basic commands, and here is the configuration: https://github.com/julien-deramond/static/blob/main/sponsorkit.config.ts.

The error is for each image:

```
Node.js v20.12.2
                                                                                                                                  7:20:46 AM
SponsorKit v0.16.1

✔ Loaded from cache ./.cache.json                                                                                                7:20:46 AM
✔ [sponsors.wide] Wrote to ./sponsors.wide.json                                                                                  7:20:46 AM
ℹ [sponsors.wide] Composing SVG...                                                                                               7:20:46 AM
node:internal/fs/promises:1049
    validateStringAfterArrayBufferView(data, 'data');
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at Object.writeFile (node:internal/fs/promises:1049:5)
    at file:///Users/ju/static/node_modules/.pnpm/sponsorkit@0.16.1/node_modules/sponsorkit/dist/cli.mjs:359:19
    at Array.map (<anonymous>)
    at applyRenderer (file:///Users/ju/static/node_modules/.pnpm/sponsorkit@0.16.1/node_modules/sponsorkit/dist/cli.mjs:337:29)
    at async run (file:///Users/ju/static/node_modules/.pnpm/sponsorkit@0.16.1/node_modules/sponsorkit/dist/cli.mjs:300:5)
    at async Object.handler (file:///Users/ju/static/node_modules/.pnpm/sponsorkit@0.16.1/node_modules/sponsorkit/dist/cli.mjs:406:5) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

### Analysis

It appears that now, the `formats` parameter is mandatory. If I add the following, the script works again:

```diff
diff --git a/sponsorkit.config.ts b/sponsorkit.config.ts
index 9028a7f..ec96179 100644
--- a/sponsorkit.config.ts
+++ b/sponsorkit.config.ts
@@ -12,6 +12,7 @@ const past: BadgePreset = {
 }
 
 export default defineConfig({
+  formats: ['svg', 'png'],
   tiers: [
     {
       title: 'Past Sponsors',
```

So, it's not an issue on my side, I'll update my project to make it work with the mandatory option, but I just wanted you to know that `formats` is now mandatory, wasn't before, in case it's an unwanted side effect :)

### Reproduction

https://github.com/julien-deramond/static/pull/7

### System Info

```Shell
System:
    OS: macOS 15.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 30.34 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.12.2 - ~/.nvm/versions/node/v20.12.2/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 10.5.0 - ~/.nvm/versions/node/v20.12.2/bin/npm
    pnpm: 9.4.0 - /opt/homebrew/bin/pnpm
  Browsers:
    Chrome: 130.0.6723.117
    Safari: 18.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by privatenumber** [comment]
Thanks for the issue! If you're interested, please feel free to open a PR for it.
